stage: "simulation"
color_bounds:
  red_lower: [0, 70, 50]
  red_upper: [10, 255, 255]
  green_lower: [25, 52, 72]
  green_upper: [102, 255, 255]
thresholds:
  red: 0.08
  green: 0.08
squares:
  - {top_left: [73, 292], bottom_right: [153, 360]}
  - {top_left: [153, 292], bottom_right: [244, 360]}
  - {top_left: [244, 292], bottom_right: [330, 360]}
  - {top_left: [61, 360], bottom_right: [150, 449]}
  - {top_left: [150, 360], bottom_right: [245, 449]}
  - {top_left: [245, 360], bottom_right: [340, 449]}
  - {top_left: [43, 449], bottom_right: [143, 550]}
  - {top_left: [143, 449], bottom_right: [246, 550]}
  - {top_left: [246, 449], bottom_right: [350, 550]}
